### ISSUE TITLE
Fix link to stable docs

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/NLPModelsKnitro.jl#76] opened 2021-10-31 18:54 UTC

**Comment by abelsiqueira** [comment] 2021-11-02 17:58
Tags should build the doc. More specifically, TagBot. It may need some update, I haven't checked. And it uses the deploy keys, which exists.

**Comment by tmigot** [comment] 2021-11-06 05:20
I think #77 should fix the trigger issue. Now, the problem is that the build will anyway fail, because `using KNITRO` or `using NLPModelsKnitro` crash.

I wrote an issue recently in KNITRO.jl to get a `KNITRO.has_knitro()` instead of returning an error.

So, we can either wait for this to be solved or modify `docs/tutorial.md` to be manually built. What do you think?

**Comment by abelsiqueira** [comment] 2021-11-06 09:39
Because it has a dev doc, I only paid attention to the TagBot issue. But actually, it doesn't build, so even the dev docs are not being built. I check the `gh-pages` and it was built 3 years ago. @dpo did it manually?

The best solution to the docs building should be the same as the CI - it should be done locally, but automated. Maybe with something like this: https://github.com/ci-for-research/self-hosted-runners/blob/master/ubuntu-docker/README.md

Alternative: modify the documentation workflow. We just need the `docs` folder because the API wouldn't be loaded. I suggested https://github.com/JuliaSmoothOptimizers/NLPModelsKnitro.jl/pull/77/files#r744105249, but maybe you'll need to modify `make.jl` as well.

**Comment by tmigot** [comment] 2022-08-15 21:53
Closed in https://github.com/JuliaSmoothOptimizers/NLPModelsKnitro.jl/pull/91

**Closed by tmigot** 2022-08-15 21:53 UTC
